name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWE0YzA2ZDgtN2NhMi00ODcxLWFkZTktMmNlZDllNTMxMTllIiwidGVuYW50X2lkIjoiMzUzMmY3NzcxNzA4ZjQ2MTAwZTVlOTdjN2MyNmFmMzBkNjYwY2JmYTVhZjljNDkzZDMxM2FhZWFmMDA4MzRmZCIsImludGVybmFsX3NlY3JldCI6IjdlMmNmMzc5LTkwYWYtNDYzZC1hYmJkLWI3YTcyZDQ5MjQ3NyJ9.2ZG4NN_7EkdbDIQqtbFBHDej5vxCdOtQ51KAt9W32eM"
TOKEN_KEY="72hdba"